2025-08-20 21:05:33,788 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 21:06:35,099 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 21:06:36,797 INFO [CENTRAL_RAD_HC] Daemon starting with 5s interval.
2025-08-20 21:06:36,798 INFO [CENTRAL_RAD_HC] Local region: us-central1, Remote region: us-east4
2025-08-20 21:06:36,798 INFO [CENTRAL_RAD_HC] Primary prefix: 10.137.245.0/25, Secondary prefix: 10.137.19.0/25
2025-08-20 21:06:39,084 INFO [CENTRAL_RAD_HC] Health Status - Local: False, Remote: True, Remote BGP: True
2025-08-20 21:06:39,085 INFO [CENTRAL_RAD_HC] State 2 -> Plan Primary=False Secondary=False
2025-08-20 21:06:47,647 ERROR [CENTRAL_RAD_HC] Unexpected error in main loop (attempt 1): <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 93, in run_loop
    primary_success = circuit_breakers['gcp_advertisement'].call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 72, in call
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 94, in <lambda>
    lambda: exponential_backoff_retry(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 119, in exponential_backoff_retry
    return func()
           ^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/gcp.py", line 169, in _update
    ).execute()
      ^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:06:54,796 INFO [CENTRAL_RAD_HC] Health Status - Local: False, Remote: True, Remote BGP: True
2025-08-20 21:06:54,796 INFO [CENTRAL_RAD_HC] State 2 -> Plan Primary=False Secondary=False
2025-08-20 21:07:03,250 ERROR [CENTRAL_RAD_HC] Unexpected error in main loop (attempt 2): <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 93, in run_loop
    primary_success = circuit_breakers['gcp_advertisement'].call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 72, in call
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 94, in <lambda>
    lambda: exponential_backoff_retry(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 119, in exponential_backoff_retry
    return func()
           ^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/gcp.py", line 169, in _update
    ).execute()
      ^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:07:05,670 INFO [CENTRAL_RAD_HC] Main loop exited. Cleanup complete.
2025-08-20 21:18:15,145 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 21:18:15,180 INFO [CENTRAL_RAD_HC] Validating GCP connectivity...
2025-08-20 21:18:15,706 INFO [CENTRAL_RAD_HC] GCP connectivity validated for project: radius-core-dev-18c6
2025-08-20 21:18:15,882 INFO [CENTRAL_RAD_HC] Validated access to region: us-central1
2025-08-20 21:18:16,100 INFO [CENTRAL_RAD_HC] Validated access to region: us-east4
2025-08-20 21:18:16,568 INFO [CENTRAL_RAD_HC] Daemon starting with 5s interval.
2025-08-20 21:18:16,568 INFO [CENTRAL_RAD_HC] Local region: us-central1, Remote region: us-east4
2025-08-20 21:18:16,568 INFO [CENTRAL_RAD_HC] Primary prefix: 10.137.245.0/25, Secondary prefix: 10.137.19.0/25
2025-08-20 21:18:17,532 WARNING [CENTRAL_RAD_HC] Unhealthy backend: https://www.googleapis.com/compute/v1/projects/radius-core-dev-18c6/zones/us-central1-c/instanceGroups/dv-c1-rac-02 in rac-anycast-us-central1-dev (radius-core-dev-18c6/us-central1)
2025-08-20 21:18:18,847 INFO [CENTRAL_RAD_HC] [radius-network-2e39/us-east4/ge4-ac-dev-pi-col-ash-cr] BGP peer statuses: {'auto-ia-bgp-ge4-dev-ac-pi-a-d48990278f40096': 'UP', 'auto-ia-bgp-ge4-dev-ac-pi-a-22fc10427ebe4f4': 'UP'}
2025-08-20 21:18:18,847 INFO [CENTRAL_RAD_HC] Health Status - Local: False, Remote: True, Remote BGP: True
2025-08-20 21:18:18,847 INFO [CENTRAL_RAD_HC] State 2 -> Plan Primary=False Secondary=False
2025-08-20 21:18:19,341 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:18:20,968 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:18:23,452 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:18:27,855 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:18:27,856 ERROR [CENTRAL_RAD_HC] Unexpected error in main loop (attempt 1): <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 93, in run_loop
    primary_success = circuit_breakers['gcp_advertisement'].call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 72, in call
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 94, in <lambda>
    lambda: exponential_backoff_retry(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 119, in exponential_backoff_retry
    return func()
           ^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/gcp.py", line 169, in _update
    ).execute()
      ^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:18:27,858 INFO [CENTRAL_RAD_HC] Main loop exited. Cleanup complete.
2025-08-20 21:26:57,411 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 21:26:57,448 INFO [CENTRAL_RAD_HC] Validating GCP connectivity...
2025-08-20 21:26:58,056 INFO [CENTRAL_RAD_HC] GCP connectivity validated for project: radius-core-dev-18c6
2025-08-20 21:26:58,250 INFO [CENTRAL_RAD_HC] Validated access to region: us-central1
2025-08-20 21:26:58,441 INFO [CENTRAL_RAD_HC] Validated access to region: us-east4
2025-08-20 21:26:59,088 CRITICAL [CENTRAL_RAD_HC] Fatal error: name 'os' is not defined
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/__main__.py", line 24, in main
    run_loop(cfg, compute)
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 42, in run_loop
    logger = logging.getLogger(os.getenv("LOGGER_NAME", "HEALTH_CHECK_DAEMON"))
                               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
2025-08-20 21:27:28,150 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 21:27:28,185 INFO [CENTRAL_RAD_HC] Validating GCP connectivity...
2025-08-20 21:27:28,634 INFO [CENTRAL_RAD_HC] GCP connectivity validated for project: radius-core-dev-18c6
2025-08-20 21:27:28,796 INFO [CENTRAL_RAD_HC] Validated access to region: us-central1
2025-08-20 21:27:29,080 INFO [CENTRAL_RAD_HC] Validated access to region: us-east4
2025-08-20 21:27:31,124 WARNING [CENTRAL_RAD_HC] Unhealthy backend: https://www.googleapis.com/compute/v1/projects/radius-core-dev-18c6/zones/us-central1-c/instanceGroups/dv-c1-rac-02 in rac-anycast-us-central1-dev (radius-core-dev-18c6/us-central1)
2025-08-20 21:27:32,429 INFO [CENTRAL_RAD_HC] [radius-network-2e39/us-east4/ge4-ac-dev-pi-col-ash-cr] BGP peer statuses: {'auto-ia-bgp-ge4-dev-ac-pi-a-d48990278f40096': 'UP', 'auto-ia-bgp-ge4-dev-ac-pi-a-22fc10427ebe4f4': 'UP'}
2025-08-20 21:27:32,846 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:27:34,155 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:27:36,457 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:27:40,945 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:28:04,183 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 21:28:40,236 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 21:28:40,270 INFO [CENTRAL_RAD_HC] Validating GCP connectivity...
2025-08-20 21:28:40,689 INFO [CENTRAL_RAD_HC] GCP connectivity validated for project: radius-core-dev-18c6
2025-08-20 21:28:40,932 INFO [CENTRAL_RAD_HC] Validated access to region: us-central1
2025-08-20 21:28:41,177 INFO [CENTRAL_RAD_HC] Validated access to region: us-east4
2025-08-20 21:28:42,577 WARNING [CENTRAL_RAD_HC] Unhealthy backend: https://www.googleapis.com/compute/v1/projects/radius-core-dev-18c6/zones/us-central1-c/instanceGroups/dv-c1-rac-02 in rac-anycast-us-central1-dev (radius-core-dev-18c6/us-central1)
2025-08-20 21:28:43,925 INFO [CENTRAL_RAD_HC] [radius-network-2e39/us-east4/ge4-ac-dev-pi-col-ash-cr] BGP peer statuses: {'auto-ia-bgp-ge4-dev-ac-pi-a-d48990278f40096': 'UP', 'auto-ia-bgp-ge4-dev-ac-pi-a-22fc10427ebe4f4': 'UP'}
2025-08-20 21:28:44,247 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:28:45,745 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:28:48,148 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 21:28:52,644 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.245.0/25 in radius-network-2e39/us-central1: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-central1/routers/gc1-dev-ac-pi-col-ord-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 23:45:30,630 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 23:47:42,448 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 23:47:42,484 CRITICAL [CENTRAL_RAD_HC] Fatal error: name 'logger' is not defined
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/__main__.py", line 23, in main
    compute = startup(cfg)
              ^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 170, in startup
    gcp_mod.validate_gcp_connectivity(cfg.gcp_project, [cfg.local_region, cfg.remote_region], compute)
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/gcp.py", line 40, in validate_gcp_connectivity
    logger.info("Validating GCP connectivity...")
    ^^^^^^
NameError: name 'logger' is not defined
2025-08-20 23:47:59,000 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 23:48:32,534 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-20 23:48:32,570 INFO [CENTRAL_RAD_HC] Validating GCP connectivity...
2025-08-20 23:48:33,007 INFO [CENTRAL_RAD_HC] GCP connectivity validated for project: radius-core-dev-18c6
2025-08-20 23:48:33,285 INFO [CENTRAL_RAD_HC] Validated access to region: us-central1
2025-08-20 23:48:33,499 INFO [CENTRAL_RAD_HC] Validated access to region: us-east4
2025-08-20 23:48:37,570 INFO [CENTRAL_RAD_HC] [radius-network-2e39/us-east4/ge4-ac-dev-pi-col-ash-cr] BGP peer statuses: {'auto-ia-bgp-ge4-dev-ac-pi-a-d48990278f40096': 'UP', 'auto-ia-bgp-ge4-dev-ac-pi-a-22fc10427ebe4f4': 'UP'}
2025-08-20 23:48:38,103 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 23:48:39,398 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 23:48:41,691 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-20 23:48:45,977 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:05,439 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-21 02:15:05,475 INFO [CENTRAL_RAD_HC] Validating GCP connectivity...
2025-08-21 02:15:05,981 INFO [CENTRAL_RAD_HC] GCP connectivity validated for project: radius-core-dev-18c6
2025-08-21 02:15:06,143 INFO [CENTRAL_RAD_HC] Validated access to region: us-central1
2025-08-21 02:15:06,333 INFO [CENTRAL_RAD_HC] Validated access to region: us-east4
2025-08-21 02:15:09,579 INFO [CENTRAL_RAD_HC] Cloudflare connectivity OK. Found 24 routes.
2025-08-21 02:15:09,580 CRITICAL [CENTRAL_RAD_HC] Fatal error: name 'os' is not defined
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/__main__.py", line 25, in main
    run_loop(cfg, compute)
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 46, in run_loop
    logger = logging.getLogger(os.getenv("LOGGER_NAME", "HEALTH_CHECK_DAEMON"))
                               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
2025-08-21 02:15:29,971 INFO [CENTRAL_RAD_HC] File logging enabled: /npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/radius_healthcheck_daemon.log
2025-08-21 02:15:30,005 INFO [CENTRAL_RAD_HC] Validating GCP connectivity...
2025-08-21 02:15:30,445 INFO [CENTRAL_RAD_HC] GCP connectivity validated for project: radius-core-dev-18c6
2025-08-21 02:15:30,719 INFO [CENTRAL_RAD_HC] Validated access to region: us-central1
2025-08-21 02:15:30,983 INFO [CENTRAL_RAD_HC] Validated access to region: us-east4
2025-08-21 02:15:31,433 INFO [CENTRAL_RAD_HC] Cloudflare connectivity OK. Found 24 routes.
2025-08-21 02:15:31,434 INFO [CENTRAL_RAD_HC] Daemon starting with 5s interval.
2025-08-21 02:15:31,440 INFO [CENTRAL_RAD_HC] Local region: us-central1, Remote region: us-east4
2025-08-21 02:15:31,440 INFO [CENTRAL_RAD_HC] Primary prefix: 10.137.245.0/25, Secondary prefix: 10.137.19.0/25
2025-08-21 02:15:34,842 INFO [CENTRAL_RAD_HC] [radius-network-2e39/us-east4/ge4-ac-dev-pi-col-ash-cr] BGP peer statuses: {'auto-ia-bgp-ge4-dev-ac-pi-a-d48990278f40096': 'UP', 'auto-ia-bgp-ge4-dev-ac-pi-a-22fc10427ebe4f4': 'UP'}
2025-08-21 02:15:34,842 INFO [CENTRAL_RAD_HC] Health Status - Local: True, Remote: True, Remote BGP: True
2025-08-21 02:15:34,842 INFO [CENTRAL_RAD_HC] State 1 -> Plan Primary=True Secondary=False
2025-08-21 02:15:35,274 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:35,275 WARNING [CENTRAL_RAD_HC] Attempt 1 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 1.00s...
2025-08-21 02:15:36,584 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:36,585 WARNING [CENTRAL_RAD_HC] Attempt 2 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 2.00s...
2025-08-21 02:15:38,885 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:38,885 WARNING [CENTRAL_RAD_HC] Attempt 3 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 4.00s...
2025-08-21 02:15:43,287 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:43,288 ERROR [CENTRAL_RAD_HC] Unexpected error in main loop (attempt 1): <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 106, in run_loop
    secondary_success = circuit_breakers['gcp_advertisement'].call(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 74, in call
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 107, in <lambda>
    lambda: exponential_backoff_retry(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 121, in exponential_backoff_retry
    return func()
           ^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/gcp.py", line 169, in _update
    ).execute()
      ^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:51,303 INFO [CENTRAL_RAD_HC] [radius-network-2e39/us-east4/ge4-ac-dev-pi-col-ash-cr] BGP peer statuses: {'auto-ia-bgp-ge4-dev-ac-pi-a-d48990278f40096': 'UP', 'auto-ia-bgp-ge4-dev-ac-pi-a-22fc10427ebe4f4': 'UP'}
2025-08-21 02:15:51,304 INFO [CENTRAL_RAD_HC] Health Status - Local: True, Remote: True, Remote BGP: True
2025-08-21 02:15:51,304 INFO [CENTRAL_RAD_HC] State 1 -> Plan Primary=True Secondary=False
2025-08-21 02:15:51,787 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:51,788 WARNING [CENTRAL_RAD_HC] Attempt 1 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 1.00s...
2025-08-21 02:15:53,083 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:53,084 WARNING [CENTRAL_RAD_HC] Attempt 2 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 2.00s...
2025-08-21 02:15:55,376 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:55,376 WARNING [CENTRAL_RAD_HC] Attempt 3 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 4.00s...
2025-08-21 02:15:59,686 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:15:59,687 ERROR [CENTRAL_RAD_HC] Unexpected error in main loop (attempt 2): <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 106, in run_loop
    secondary_success = circuit_breakers['gcp_advertisement'].call(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 74, in call
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 107, in <lambda>
    lambda: exponential_backoff_retry(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 121, in exponential_backoff_retry
    return func()
           ^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/gcp.py", line 169, in _update
    ).execute()
      ^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:07,808 INFO [CENTRAL_RAD_HC] [radius-network-2e39/us-east4/ge4-ac-dev-pi-col-ash-cr] BGP peer statuses: {'auto-ia-bgp-ge4-dev-ac-pi-a-d48990278f40096': 'UP', 'auto-ia-bgp-ge4-dev-ac-pi-a-22fc10427ebe4f4': 'UP'}
2025-08-21 02:16:07,809 INFO [CENTRAL_RAD_HC] Health Status - Local: True, Remote: True, Remote BGP: True
2025-08-21 02:16:07,809 INFO [CENTRAL_RAD_HC] State 1 -> Plan Primary=True Secondary=False
2025-08-21 02:16:08,288 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:08,289 WARNING [CENTRAL_RAD_HC] Attempt 1 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 1.00s...
2025-08-21 02:16:09,591 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:09,592 WARNING [CENTRAL_RAD_HC] Attempt 2 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 2.00s...
2025-08-21 02:16:11,891 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:11,892 WARNING [CENTRAL_RAD_HC] Attempt 3 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 4.00s...
2025-08-21 02:16:16,189 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:16,190 ERROR [CENTRAL_RAD_HC] Unexpected error in main loop (attempt 3): <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 106, in run_loop
    secondary_success = circuit_breakers['gcp_advertisement'].call(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 74, in call
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 107, in <lambda>
    lambda: exponential_backoff_retry(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 121, in exponential_backoff_retry
    return func()
           ^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/gcp.py", line 169, in _update
    ).execute()
      ^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:24,577 INFO [CENTRAL_RAD_HC] [radius-network-2e39/us-east4/ge4-ac-dev-pi-col-ash-cr] BGP peer statuses: {'auto-ia-bgp-ge4-dev-ac-pi-a-d48990278f40096': 'UP', 'auto-ia-bgp-ge4-dev-ac-pi-a-22fc10427ebe4f4': 'UP'}
2025-08-21 02:16:24,578 INFO [CENTRAL_RAD_HC] Health Status - Local: True, Remote: True, Remote BGP: True
2025-08-21 02:16:24,578 INFO [CENTRAL_RAD_HC] State 1 -> Plan Primary=True Secondary=False
2025-08-21 02:16:25,086 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:25,086 WARNING [CENTRAL_RAD_HC] Attempt 1 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 1.00s...
2025-08-21 02:16:26,390 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:26,390 WARNING [CENTRAL_RAD_HC] Attempt 2 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 2.00s...
2025-08-21 02:16:28,687 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:28,687 WARNING [CENTRAL_RAD_HC] Attempt 3 failed for _update: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">. Retrying in 4.00s...
2025-08-21 02:16:32,993 ERROR [CENTRAL_RAD_HC] Permanent error updating BGP advertisement for 10.137.19.0/25 in radius-network-2e39/us-east4: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:32,993 ERROR [CENTRAL_RAD_HC] Unexpected error in main loop (attempt 4): <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
Traceback (most recent call last):
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 106, in run_loop
    secondary_success = circuit_breakers['gcp_advertisement'].call(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 74, in call
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/daemon.py", line 107, in <lambda>
    lambda: exponential_backoff_retry(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/circuit.py", line 121, in exponential_backoff_retry
    return func()
           ^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/src/mt_gcp_daemon/gcp.py", line 169, in _update
    ).execute()
      ^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/npm-services/pylon/local-projects/GitHub-Projects/mt-gcp-daemon-modularized/.venv/lib/python3.12/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr?alt=json returned "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'". Details: "[{'message': "Required 'compute.routers.update' permission for 'projects/radius-network-2e39/regions/us-east4/routers/ge4-ac-dev-pi-col-ash-cr'", 'domain': 'global', 'reason': 'forbidden'}]">
2025-08-21 02:16:32,995 INFO [CENTRAL_RAD_HC] Main loop exited. Cleanup complete.
